buildCommand: |
  curl https://pyenv.run | bash
  export PATH="$HOME/.pyenv/bin:$PATH"
  eval "$(pyenv init --path)"
  eval "$(pyenv init -)"
  pyenv install 3.10.13
  pyenv global 3.10.13
  python --version  # для перевірки
  pip install -r requirements.txt