services:
  - type: web
    name: euro-bot
    env: python
    buildCommand: |
      pyenv install 3.10.13 && pyenv global 3.10.13
      pip install -r requirements.txt
    startCommand: python euro_bot_renew.py